# Generated by Django 5.2.13 on 2026-04-22 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='target_grade',
            field=models.FloatField(blank=True, help_text='هدف نمره (اختیاری)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='chapters_remaining',
            field=models.IntegerField(help_text='تعداد فصل\u200cهای باقی\u200cمانده', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(help_text='تاریخ امتحان'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='study_hours_remaining',
            field=models.FloatField(help_text='ساعت مطالعه باقی\u200cمانده', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='daily_available_hours',
            field=models.FloatField(help_text='ساعت آزاد روزانه برای مطالعه', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='plan_data',
            field=models.JSONField(default=dict, help_text='برنامه مطالعه روزانه به صورت JSON'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='difficulty',
            field=models.IntegerField(help_text='سختی درس از 1 تا 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='target_score',
        ),
    ]
