# Generated by Django 5.2.17 on 2026-08-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_exam_chapters_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='notes',
            field=models.TextField(blank=True, help_text='یادداشت کوتاه درباره\u200cی درس (اختیاری)', null=True),
        ),
    ]
