# Generated by Django 5.2.17 on 2026-08-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_subject_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='notes',
            field=models.TextField(blank=True, help_text='یادداشت اختیاری درباره\u200cی امتحان', null=True),
        ),
    ]
