# Generated by Django 5.2.17 on 2026-09-03 06:37

import django.core.validators
from django.db import migrations, models


def backfill_hours_deducted(apps, schema_editor):
    """
    گزارش‌های ثبت‌شده «قبل» از این Migration مقدارِ hours_deducted ندارند
    (ستونِ جدید برای همه‌ی ردیف‌های موجود با 0.0 پر می‌شود). عددِ دقیقِ
    کسرشده‌ی تاریخی قابلِ بازیابی نیست؛ بهترین تخمینِ ممکن این است که فرض
    کنیم «کلِ ساعتِ ثبت‌شده» کسر شده است — که در حالتِ عادی (امتحانِ
    ناتمام) دقیقاً همان رفتارِ save() قدیمی است. فقط در حالتِ استثنایی که
    ساعتِ امتحان موقعِ ثبت از قبل تمام بوده، این تخمین بیشتر از کسرِ واقعی
    است؛ این سازش‌کاری آگاهانه و مستندشده است.
    """
    StudyLog = apps.get_model('planner', 'StudyLog')
    StudyLog.objects.update(hours_deducted=models.F('hours_studied'))


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_exam_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylog',
            name='hours_deducted',
            field=models.FloatField(default=0.0, help_text='ساعتِ واقعاً کسرشده از امتحان (مبنای بازگرداندن هنگام حذف)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        # پرکردنِ ستونِ جدید برای گزارش‌های قدیمی (تخمینِ مستندشده؛
        # شرح در docstring تابعِ بالا). reverse عمداً noop است چون مقدارِ
        # دقیقِ تاریخی برای بازگشت وجود ندارد.
        migrations.RunPython(backfill_hours_deducted, migrations.RunPython.noop),
    ]
