# Generated by Django 5.2.17 on 2026-09-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def deduplicate_study_plans(apps, schema_editor):
    """
    پیش‌نیازِ اعمالِ قیدِ یکتایی: اگر در دیتابیسِ قدیمی برای کاربری بیش
    از یک رکوردِ StudyPlan وجود داشته باشد (مثلاً حاصلِ Race Condition در
    نسخه‌هایِ قبل)، اعمالِ قیدِ UNIQUE با IntegrityError شکست می‌خورد. این تابع برای هر کاربرِ دارایِ تکرار فقط جدیدترین رکورد را
    نگه می‌دارد (بیشترین created_at و سپس id) و بقیه را حذف
    می‌کند؛ چون daily_available_hours همان تنظیمِ نهاییِ کاربر است و
    plan_data صرفاً مرجع/کش است که در اولین بازدیدِ بعدی از نو محاسبه
    می‌شود، این سیاست بدونِ ازدست‌دادنِ داده‌یِ معنادار است.
    """
    StudyPlan = apps.get_model('planner', 'StudyPlan')
    users_with_duplicates = (
        StudyPlan.objects.values('user_id')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    for row in users_with_duplicates:
        newest = (
            StudyPlan.objects.filter(user_id=row['user_id'])
            .order_by('-created_at', '-id')
            .first()
        )
        StudyPlan.objects.filter(user_id=row['user_id']).exclude(pk=newest.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_studylog_hours_deducted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # اول پاکسازیِ رکوردهایِ تکراریِ احتمالی (شرح در docstringِ بالا)،
        # بعد اعمالِ قید — وگرنه ALTER TABLE روی داده‌یِ تکراری شکست می‌خورد.
        # reverse عمداً noop است چون رکوردهایِ حذف‌شده قابلِ بازیابی نیستند (و قید هم برمی‌گردد ولی داده خیر).
        migrations.RunPython(deduplicate_study_plans, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studyplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
