# Generated by Django 5.2.17 on 2026-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_securityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurityprofile',
            name='last_used_totp_step',
            field=models.BigIntegerField(blank=True, help_text='آخرینِ گامِ زمانیِ مصرف\u200cشده (ضدِ replay)', null=True),
        ),
        migrations.AddField(
            model_name='usersecurityprofile',
            name='totp_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='لحظه\u200cی فعال\u200cسازیِ 2FA (NULL = هنوز تأییدنشده/خاموش)', null=True),
        ),
        migrations.AddField(
            model_name='usersecurityprofile',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='کلیدِ TOTP به base32 (فقط وقتی معتبر است که confirmed پر باشد)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'ورود موفق'), ('login_failed', 'تلاشِ ناموفقِ ورود'), ('password_changed', 'تغییر رمز عبور'), ('password_reset_requested', 'درخواستِ بازیابیِ رمزِ عبور'), ('password_reset_completed', 'بازنشانیِ رمزِ عبور'), ('two_factor_enabled', 'فعال\u200cسازیِ ورودِ دومرحله\u200cای'), ('two_factor_disabled', 'خاموش\u200cشدنِ ورودِ دومرحله\u200cای'), ('login_2fa_failed', 'کدِ نامعتبرِ ورودِ دومرحله\u200cای')], max_length=40),
        ),
    ]
