# Generated by Django 5.2.17 on 2026-09-16 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_usersecurityprofile_last_used_totp_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'ورود موفق'), ('login_failed', 'تلاشِ ناموفقِ ورود'), ('password_changed', 'تغییر رمز عبور'), ('password_reset_requested', 'درخواستِ بازیابیِ رمزِ عبور'), ('password_reset_completed', 'بازنشانیِ رمزِ عبور'), ('two_factor_enabled', 'فعال\u200cسازیِ ورودِ دومرحله\u200cای'), ('two_factor_disabled', 'خاموش\u200cشدنِ ورودِ دومرحله\u200cای'), ('login_2fa_failed', 'کدِ نامعتبرِ ورودِ دومرحله\u200cای'), ('login_new_address', 'ورود از نشانیِ جدید')], max_length=40),
        ),
        migrations.CreateModel(
            name='KnownLoginAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_login_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'ip_address'), name='known_addr_user_ip_uniq')],
            },
        ),
    ]
