"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# از 2026-09-06 مقادیرِ حساس از «متغیرهایِ محیطی» خوانده می‌شوند؛ اگر ست
# نشده باشند، همان مقدارِ توسعه (dev) قبلی اعمال می‌شود تا اجرایِ محلیِ
# بدونِ هیچ متغیری ذره‌ای تغییر نکند. مقادیرِ بولیِ مثبتِ پذیرفته:
# 1 / true / yes / on (بدونِ حساسیت به بزرگ/کوچکی).


def _env_bool(name, default=False):
    """متغیرِ محیطی را به‌عنوانِ boolean می‌خواند (فقط مقادیرِ مثبتِ صریح)."""
    raw = os.environ.get(name)
    if raw is None or raw.strip() == '':
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    """متغیرِ محیطیِ «جدا‌شده با کاما» را به فهرستِ تمیزشده تبدیل می‌کند."""
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


# کلیدِ توسعه: فقط مناسبِ اجرایِ محلی است (چون در مخزنِ عمومی دیده می‌شود).
# برایِ Production متغیرِ DJANGO_SECRET_KEY را با یک کلیدِ واقعی ست کنید:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
_DEV_SECRET_KEY = 'django-insecure-_2yv1re!edx4&9c5+=2e)t37xml-dnc5s08-5%#s++a%9awr-n'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _DEV_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True یعنی خطاها با جزئیاتِ کامل (Traceback) در مرورگر نمایش داده
# می‌شوند و فایل‌های استاتیک هم خودکار سرو می‌شوند؛ این حالت فقط برای
# توسعه‌ی محلی مناسب است، نه برای انتشار واقعیِ سایت (Production).
DEBUG = _env_bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')

# سپرِ راه‌اندازیِ Production: اجرا در حالتِ DEBUG=false با کلیدِ توسعه یا
# بدونِ ALLOWED_HOSTS از همانِ ابتدا با پیامِ روشنِ راهنما متوقف می‌شود —
# بهتر از بوتِ بی‌صدا در حالتِ ناامن یا خطاهایِ ۴۰۰ِ گیج‌کننده‌ی بعداً.
if not DEBUG:
    if SECRET_KEY == _DEV_SECRET_KEY:
        raise ImproperlyConfigured(
            'Production mode (DJANGO_DEBUG=false) requires a real DJANGO_SECRET_KEY '
            'instead of the development key. Generate one with: '
            'python -c "from django.core.management.utils import '
            'get_random_secret_key; print(get_random_secret_key())"'
        )
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            'Production mode (DJANGO_DEBUG=false) requires DJANGO_ALLOWED_HOSTS '
            '(comma-separated hosts, e.g. "example.com,www.example.com").'
        )


# Application definition

# فهرست همه‌ی اپلیکیشن‌هایی که جنگو باید بارگذاری کند؛ به سه دسته تقسیم می‌شود:
INSTALLED_APPS = [
    # اپلیکیشن‌های داخلیِ خودِ جنگو (پنل ادمین، احراز هویت، فایل استاتیک و...)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party
    # کتابخانه‌های شخص‌ثالثی که با pip نصب شده‌اند (در requirements.txt هم هستند)
    'rest_framework',            # فریم‌ورک ساختِ API (سریالایزر، ویوست و...)
    'rest_framework_simplejwt',  # احراز هویت مبتنی بر JWT
    # اپِ «لیستِ سیاهِ توکن‌ها»یِ SimpleJWT (از 2026-09-08): دو جدولِ
    # OutstandingToken (توکن‌های صادرشده) و BlacklistedToken (توکن‌های باطل‌شده)
    # را به دیتابیس اضافه می‌کند؛ لازمه‌ی چرخش/ابطالِ توکنِ Refresh است
    # (مایگریشن‌هایش داخلِ خودِ کتابخانه است؛ فقط یک‌بار migrate لازم دارد).
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',               # مدیریت هدرهای CORS

    # local apps
    # اپلیکیشنِ خودِ ما که تمام منطق پروژه در آن است
    'planner',
]


# میان‌افزارها (Middleware): کدی که روی *هر* درخواست/پاسخ، قبل از رسیدن
# به View (و بعد از خروج از آن)، به‌ترتیب همین لیست اجرا می‌شود.
MIDDLEWARE = [
    # باید نزدیک بالای لیست باشد تا هدرهای CORS به همه‌ی پاسخ‌ها اضافه شود
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# فایلی که نقشه‌ی اصلیِ مسیرهای کل پروژه در آن است (همان backend/urls.py)
ROOT_URLCONF = 'backend.urls'

# تنظیماتِ موتور Templateهای جنگو؛ چون فرانت‌اند این پروژه جدا (استاتیک) است
# و از Django Template استفاده نمی‌کند، این بخش عملاً کمتر به‌کار می‌آید،
# ولی چون پنل ادمین به آن نیاز دارد، حذف نشده است.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# از 2026-09-09: موتورِ دیتابیس از متغیرِ محیطیِ DATABASE_URL خوانده می‌شود —
# با «پیش‌فرضِ امنِ توسعه»: بدونِ این متغیر دقیقاً همان SQLiteِ قبلی
# (فایلِ db.sqlite3) فعال می‌شود و هیچ رفتاری عوض نمی‌شود. برای
# PostgreSQL (چندکاربره/Production) آدرسِ کامل را ست کنید، مثل:
#   set DATABASE_URL=postgres://user:pass@localhost:5432/plannerdb
# پارامترهایِ اختیاریِ انتهایِ URL:
#   ?sslmode=require        → گزینه‌ی sslmode درایورِ psycopg
#   ?conn_max_age=60        → اتصالِ ماندگار (CONN_MAX_AGE جنگو)
#   ?host=/var/run/postgresql → مسیرِ سوکتِ یونیکس به‌جایِ TCP (لینوکس)
# درایورِ psycopg لازم است و در requirements.txt اعلام شده است
# (نصب: pip install -r requirements.txt). رمزِ عبوری که کاراکترِ خاص دارد
# باید URL-encode شود (مثلاً @ → %40).

def _resolve_database(env=None, import_module=None):
    """متغیرِ DATABASE_URL را به تنظیماتِ DATABASES['default'] ترجمه می‌کند.

    - بدونِ متغیر (یا خالی) → همان SQLiteِ توسعه‌ی قبل، دست‌نخورده.
    - postgres:// یا postgresql:// → موتورِ PostgreSQL جنگو.
    - هر خطایِ پیکربندی (scheme نامعتبر، پورتِ غیر عددی، نبودِ نامِ
      دیتابیس، نبودِ درایورِ psycopg) همان موقع و با پیامِ راهنما
      متوقف می‌شود (ImproperlyConfigured) — نه وسطِ اولین کوئری.

    پارامترهایِ env و import_module فقط برای تست‌پذیری‌اند (تزریقِ
    محیطِ ساختگی و شبیه‌سازیِ نبودِ درایور بدونِ دست‌زدن به سیستم).
    """
    from urllib.parse import urlsplit, parse_qs, unquote

    if env is None:
        env = os.environ
    if import_module is None:
        from importlib import import_module as _default_import
        import_module = _default_import

    raw = (env.get('DATABASE_URL') or '').strip()
    if not raw:
        # پیش‌فرضِ امنِ توسعه — دقیقاً همانِ قبل از این تغییر:
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    parts = urlsplit(raw)
    scheme = parts.scheme.lower()
    if scheme not in ('postgres', 'postgresql'):
        raise ImproperlyConfigured(
            f'DATABASE_URL: only postgres:// or postgresql:// URLs are '
            f'supported (got scheme: {scheme or "empty"}). For SQLite, '
            f'simply unset DATABASE_URL — the development default applies.'
        )

    name = parts.path.lstrip('/')
    if not name:
        raise ImproperlyConfigured(
            'DATABASE_URL: database name is missing from the URL path, '
            'e.g. postgres://user:pass@localhost:5432/plannerdb.'
        )

    try:
        port = parts.port
    except ValueError:
        raise ImproperlyConfigured(
            f'DATABASE_URL: port must be numeric, e.g. '
            f'postgres://user:pass@localhost:5432/{name} (got: {raw!r}).'
        )

    query = parse_qs(parts.query)
    # «?host=» مسیرِ سوکتِ یونیکس را ممکن می‌کند (الگویِ رایج در هاست‌هایِ
    # ابری) و بر hostnameِ داخلِ URL اولویت دارد.
    if query.get('host'):
        host = unquote(query['host'][0])
    else:
        host = parts.hostname or ''

    database = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': name,
        'USER': unquote(parts.username or ''),
        'PASSWORD': unquote(parts.password or ''),
        'HOST': host,
        'PORT': str(port) if port else '',
    }

    if query.get('sslmode'):
        database['OPTIONS'] = {'sslmode': query['sslmode'][0]}

    if query.get('conn_max_age'):
        try:
            conn_max_age = int(query['conn_max_age'][0])
        except ValueError:
            raise ImproperlyConfigured(
                'DATABASE_URL: conn_max_age query parameter must be an '
                f'integer number of seconds (got: {query["conn_max_age"][0]!r}).'
            )
        if conn_max_age < 0:
            raise ImproperlyConfigured(
                'DATABASE_URL: conn_max_age must be >= 0 (0 = close after '
                'each request, N = keep the connection open for N seconds).'
            )
        database['CONN_MAX_AGE'] = conn_max_age

    # بررسیِ درایور در آخرین گام: خطاهایِ URL خودشان پیامِ روشن‌تر دارند؛
    # اینجا فقط مطمئن می‌شویم psycopg (نسخه‌ی ۳) واقعاً import می‌شود.
    try:
        import_module('psycopg')
    except ImportError:
        raise ImproperlyConfigured(
            'DATABASE_URL points to PostgreSQL, but the psycopg driver is '
            'not installed. Run: pip install "psycopg[binary]"  '
            '(or pip install -r requirements.txt)'
        )
    return database


DATABASES = {'default': _resolve_database()}

# هشدارِ یک‌خطی برای «Production روی SQLite»: بستنِ چشم به این حالت، یعنی
# اجرایِ نمایشیِ بدونِ کاربرِ هم‌زمان — قابل‌قبول برای دمو/دفاع، نه انتشارِ
# واقعی. فقط روی stderr نوشته می‌شود و بوت را متوقف نمی‌کند (سپرِ سختِ
# Production در بالایِ همین فایل همان‌جا که باید، ایستاده است).
if not DEBUG and DATABASES['default']['ENGINE'].endswith('sqlite3'):
    import sys as _sys
    _sys.stderr.write(
        'Warning: DJANGO_DEBUG=false is running on SQLite. This is fine for '
        'a local demo, but for real multi-user production set DATABASE_URL '
        'to a PostgreSQL server.\n'
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# این قوانین، پیش از ذخیره‌ی هر رمز عبورِ جدید بررسی می‌شوند (مثلاً نباید
# خیلی شبیهِ نامِ کاربری باشد، نباید خیلی کوتاه یا کاملاً عددی باشد و...)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# به جنگو می‌گوید علاوه بر فایل‌های استاتیکِ داخلِ هر اپ، پوشه‌ی static/
# پروژه (که رابط کاربریِ HTML/CSS/JS ما در آن است) را هم سرو کند. برای
# همین است که می‌شود صفحاتی مثل index.html را مستقیماً روی همین سرور
# جنگو (زیرِ آدرسِ /static/...) باز کرد.
STATICFILES_DIRS = [
    BASE_DIR.parent / 'static', 
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# اجازه می‌دهد از هر دامنه/مبدأیی (حتی وقتی فرانت‌اند روی پورتِ دیگری اجرا
# شود) به این API درخواست زده شود. مناسبِ توسعه است؛ برای انتشارِ واقعی
# باید با CORS_ALLOWED_ORIGINS به دامنه‌ی مشخصِ فرانت‌اند محدود شود.
CORS_ALLOW_ALL_ORIGINS = _env_bool('DJANGO_CORS_ALLOW_ALL', default=True)

# وقتی DJANGO_CORS_ALLOW_ALL=false است فقط این مبدأها مجازند (با کاما جدا
# کنید و scheme کامل بنویسید، مثلِ https://example.com). در حالتِ توسعه
# خالی می‌ماند چون allow-all فعال است.
CORS_ALLOWED_ORIGINS = _env_list('DJANGO_ALLOWED_ORIGINS')

# REST Framework settings
# تنظیماتِ سراسریِ DRF: همه‌ی Viewها به‌صورت پیش‌فرض این دو رفتار را دارند
# مگر این‌که در خودِ آن View چیز دیگری مشخص شده باشد.
REST_FRAMEWORK = {
    # روش شناساییِ کاربر از روی هر درخواست: خواندنِ توکن JWT از هدر Authorization
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # پیش‌فرض: هیچ درخواستی بدونِ احراز هویت پذیرفته نمی‌شود (مگر با
    # @permission_classes([AllowAny]) صراحتاً اجازه داده شود، مثل register/login)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# JWT settings
from datetime import timedelta

# تنظیماتِ کتابخانه‌ی djangorestframework-simplejwt
SIMPLE_JWT = {
    # توکنِ «دسترسی» که در هر درخواست فرستاده می‌شود، ۱ روز اعتبار دارد
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    # توکنِ «تمدید» که برای گرفتنِ توکنِ دسترسیِ تازه استفاده می‌شود، ۷ روز اعتبار دارد
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # چرخشِ توکنِ Refresh (از 2026-09-08): هر تمدید، علاوه بر توکنِ دسترسیِ
    # تازه، یک توکنِ Refreshِ تازه هم صادر می‌کند؛ فرانت‌اند آن را ذخیره
    # می‌کند (تابعِ refreshAccessToken در app.js از قبل آماده بود).
    'ROTATE_REFRESH_TOKENS': True,
    # توکنِ Refreshِ «قبلی» بلافاصله بعد از چرخش باطل می‌شود (لیستِ سیاه)؛
    # یعنی هر توکنِ تمدید فقط یک‌بار قابلِ استفاده است — توکنِ دزدیده‌شده
    # با اولین تمدیدِ مالکِ واقعی، بی‌اعتبار می‌شود. خروجِ سرور-محور هم
    # (POST /api/auth/logout/) با همین سازوکار توکن را باطل می‌کند.
    'BLACKLIST_AFTER_ROTATION': True,
    # یعنی هدر باید به‌شکلِ Authorization: Bearer <token> فرستاده شود
    'AUTH_HEADER_TYPES': ('Bearer',),
}
