"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# از 2026-09-06 مقادیرِ حساس از «متغیرهایِ محیطی» خوانده می‌شوند؛ اگر ست
# نشده باشند، همان مقدارِ توسعه (dev) قبلی اعمال می‌شود تا اجرایِ محلیِ
# بدونِ هیچ متغیری ذره‌ای تغییر نکند. مقادیرِ بولیِ مثبتِ پذیرفته:
# 1 / true / yes / on (بدونِ حساسیت به بزرگ/کوچکی).


def _env_bool(name, default=False):
    """متغیرِ محیطی را به‌عنوانِ boolean می‌خواند (فقط مقادیرِ مثبتِ صریح)."""
    raw = os.environ.get(name)
    if raw is None or raw.strip() == '':
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    """متغیرِ محیطیِ «جدا‌شده با کاما» را به فهرستِ تمیزشده تبدیل می‌کند."""
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


def _env_throttle_rate(name, default):
    """متغیرِ محیطیِ «نرخِ محدودسازی» را با اعتبارسنجیِ سخت‌گیرانه می‌خواند.

    قالبِ معتبر: '<عدد>/<sec|min|hour|day>' مثلِ '20/min'. مقدارِ نامعتبر
    (مثلِ '20/hourly' یا '20') همانِ بوت با پیامِ راهنما متوقف می‌کند —
    الگویِ fail-fastِ DATABASE_URL: مقدارِ غلطِ محیط نباید بی‌صدا محدودسازی
    را از کار بیندازد. بی‌مقدار → همان مقدارِ پیش‌فرضِ توسعه.
    """
    raw = os.environ.get(name)
    if raw is None or raw.strip() == '':
        return default
    rate = raw.strip()
    if not re.fullmatch(r'\d+/(?:sec|min|hour|day)', rate):
        raise ImproperlyConfigured(
            f'{name} must look like "20/min" — a number followed by one of '
            f'/sec, /min, /hour, /day (got: {rate!r}). Leave it unset to use '
            f'the development default ({default}).'
        )
    return rate


def _env_int(name, default=0):
    """متغیرِ محیطیِ عددیِ صحیح (مثلِ ثانیه‌هایِ HSTS) — نامعتبر = بوت با پیام.

    فقط خودِ تبدیلِ int اینجا انجام می‌شود؛ قیودِ معنایی (مثلِ «نمی‌تواند
    منفی باشد») جایِ استفاده ست می‌شود تا پیامِ خطا دقیق و محلی بماند.
    """
    raw = os.environ.get(name)
    if raw is None or raw.strip() == '':
        return default
    try:
        return int(raw.strip())
    except ValueError:
        raise ImproperlyConfigured(
            f'{name} must be an integer number (got: {raw.strip()!r}).'
        )


def _env_proxy_ssl_header(name):
    """متغیرِ «HEADER,value» را به تاپلِ SECURE_PROXY_SSL_HEADER ترجمه می‌کند.

    مثلِ 'HTTP_X_FORWARDED_PROTO,https' → ('HTTP_X_FORWARDED_PROTO', 'https').
    خالی/ست‌نشده → None (رفتارِ پیش‌فرضِ جنگو)؛ قالبِ ناقص = بوت با پیامِ
    راهنما (fail-fast، هم‌الگویِ بالا).
    """
    raw = (os.environ.get(name) or '').strip()
    if not raw:
        return None
    parts = [part.strip() for part in raw.split(',')]
    if len(parts) != 2 or not all(parts):
        raise ImproperlyConfigured(
            f'{name} must be "HEADER,value" (comma-separated), e.g. '
            f'"HTTP_X_FORWARDED_PROTO,https" (got: {raw!r}).'
        )
    return tuple(parts)


# کلیدِ توسعه: فقط مناسبِ اجرایِ محلی است (چون در مخزنِ عمومی دیده می‌شود).
# برایِ Production متغیرِ DJANGO_SECRET_KEY را با یک کلیدِ واقعی ست کنید:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
_DEV_SECRET_KEY = 'django-insecure-_2yv1re!edx4&9c5+=2e)t37xml-dnc5s08-5%#s++a%9awr-n'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _DEV_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True یعنی خطاها با جزئیاتِ کامل (Traceback) در مرورگر نمایش داده
# می‌شوند و فایل‌های استاتیک هم خودکار سرو می‌شوند؛ این حالت فقط برای
# توسعه‌ی محلی مناسب است، نه برای انتشار واقعیِ سایت (Production).
DEBUG = _env_bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')

# سپرِ راه‌اندازیِ Production: اجرا در حالتِ DEBUG=false با کلیدِ توسعه یا
# بدونِ ALLOWED_HOSTS از همانِ ابتدا با پیامِ روشنِ راهنما متوقف می‌شود —
# بهتر از بوتِ بی‌صدا در حالتِ ناامن یا خطاهایِ ۴۰۰ِ گیج‌کننده‌ی بعداً.
if not DEBUG:
    if SECRET_KEY == _DEV_SECRET_KEY:
        raise ImproperlyConfigured(
            'Production mode (DJANGO_DEBUG=false) requires a real DJANGO_SECRET_KEY '
            'instead of the development key. Generate one with: '
            'python -c "from django.core.management.utils import '
            'get_random_secret_key; print(get_random_secret_key())"'
        )
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            'Production mode (DJANGO_DEBUG=false) requires DJANGO_ALLOWED_HOSTS '
            '(comma-separated hosts, e.g. "example.com,www.example.com").'
        )


# Application definition

# فهرست همه‌ی اپلیکیشن‌هایی که جنگو باید بارگذاری کند؛ به سه دسته تقسیم می‌شود:
INSTALLED_APPS = [
    # اپلیکیشن‌های داخلیِ خودِ جنگو (پنل ادمین، احراز هویت، فایل استاتیک و...)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party
    # کتابخانه‌های شخص‌ثالثی که با pip نصب شده‌اند (در requirements.txt هم هستند)
    'rest_framework',            # فریم‌ورک ساختِ API (سریالایزر، ویوست و...)
    'rest_framework_simplejwt',  # احراز هویت مبتنی بر JWT
    # اپِ «لیستِ سیاهِ توکن‌ها»یِ SimpleJWT (از 2026-09-08): دو جدولِ
    # OutstandingToken (توکن‌های صادرشده) و BlacklistedToken (توکن‌های باطل‌شده)
    # را به دیتابیس اضافه می‌کند؛ لازمه‌ی چرخش/ابطالِ توکنِ Refresh است
    # (مایگریشن‌هایش داخلِ خودِ کتابخانه است؛ فقط یک‌بار migrate لازم دارد).
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',               # مدیریت هدرهای CORS

    # local apps
    # اپلیکیشنِ خودِ ما که تمام منطق پروژه در آن است
    'planner',
]


# میان‌افزارها (Middleware): کدی که روی *هر* درخواست/پاسخ، قبل از رسیدن
# به View (و بعد از خروج از آن)، به‌ترتیب همین لیست اجرا می‌شود.
MIDDLEWARE = [
    # باید نزدیک بالای لیست باشد تا هدرهای CORS به همه‌ی پاسخ‌ها اضافه شود
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # چندزبانی (از 2026-09-09): زبانِ فعالِ هر درخواست را از هدرِ استانداردِ
    # Accept-Language تعیین می‌کند (fallback = LANGUAGE_CODE)؛ طبقِ مستندِ جنگو
    # باید بعد از SessionMiddleware و قبل از CommonMiddleware باشد.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# فایلی که نقشه‌ی اصلیِ مسیرهای کل پروژه در آن است (همان backend/urls.py)
ROOT_URLCONF = 'backend.urls'

# تنظیماتِ موتور Templateهای جنگو؛ چون فرانت‌اند این پروژه جدا (استاتیک) است
# و از Django Template استفاده نمی‌کند، این بخش عملاً کمتر به‌کار می‌آید،
# ولی چون پنل ادمین به آن نیاز دارد، حذف نشده است.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# از 2026-09-09: موتورِ دیتابیس از متغیرِ محیطیِ DATABASE_URL خوانده می‌شود —
# با «پیش‌فرضِ امنِ توسعه»: بدونِ این متغیر دقیقاً همان SQLiteِ قبلی
# (فایلِ db.sqlite3) فعال می‌شود و هیچ رفتاری عوض نمی‌شود. برای
# PostgreSQL (چندکاربره/Production) آدرسِ کامل را ست کنید، مثل:
#   set DATABASE_URL=postgres://user:pass@localhost:5432/plannerdb
# پارامترهایِ اختیاریِ انتهایِ URL:
#   ?sslmode=require        → گزینه‌ی sslmode درایورِ psycopg
#   ?conn_max_age=60        → اتصالِ ماندگار (CONN_MAX_AGE جنگو)
#   ?host=/var/run/postgresql → مسیرِ سوکتِ یونیکس به‌جایِ TCP (لینوکس)
# درایورِ psycopg لازم است و در requirements.txt اعلام شده است
# (نصب: pip install -r requirements.txt). رمزِ عبوری که کاراکترِ خاص دارد
# باید URL-encode شود (مثلاً @ → %40).

def _resolve_database(env=None, import_module=None):
    """متغیرِ DATABASE_URL را به تنظیماتِ DATABASES['default'] ترجمه می‌کند.

    - بدونِ متغیر (یا خالی) → همان SQLiteِ توسعه‌ی قبل، دست‌نخورده.
    - postgres:// یا postgresql:// → موتورِ PostgreSQL جنگو.
    - هر خطایِ پیکربندی (scheme نامعتبر، پورتِ غیر عددی، نبودِ نامِ
      دیتابیس، نبودِ درایورِ psycopg) همان موقع و با پیامِ راهنما
      متوقف می‌شود (ImproperlyConfigured) — نه وسطِ اولین کوئری.

    پارامترهایِ env و import_module فقط برای تست‌پذیری‌اند (تزریقِ
    محیطِ ساختگی و شبیه‌سازیِ نبودِ درایور بدونِ دست‌زدن به سیستم).
    """
    from urllib.parse import urlsplit, parse_qs, unquote

    if env is None:
        env = os.environ
    if import_module is None:
        from importlib import import_module as _default_import
        import_module = _default_import

    raw = (env.get('DATABASE_URL') or '').strip()
    if not raw:
        # پیش‌فرضِ امنِ توسعه — دقیقاً همانِ قبل از این تغییر:
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    parts = urlsplit(raw)
    scheme = parts.scheme.lower()
    if scheme not in ('postgres', 'postgresql'):
        raise ImproperlyConfigured(
            f'DATABASE_URL: only postgres:// or postgresql:// URLs are '
            f'supported (got scheme: {scheme or "empty"}). For SQLite, '
            f'simply unset DATABASE_URL — the development default applies.'
        )

    name = parts.path.lstrip('/')
    if not name:
        raise ImproperlyConfigured(
            'DATABASE_URL: database name is missing from the URL path, '
            'e.g. postgres://user:pass@localhost:5432/plannerdb.'
        )

    try:
        port = parts.port
    except ValueError:
        raise ImproperlyConfigured(
            f'DATABASE_URL: port must be numeric, e.g. '
            f'postgres://user:pass@localhost:5432/{name} (got: {raw!r}).'
        )

    query = parse_qs(parts.query)
    # «?host=» مسیرِ سوکتِ یونیکس را ممکن می‌کند (الگویِ رایج در هاست‌هایِ
    # ابری) و بر hostnameِ داخلِ URL اولویت دارد.
    if query.get('host'):
        host = unquote(query['host'][0])
    else:
        host = parts.hostname or ''

    database = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': name,
        'USER': unquote(parts.username or ''),
        'PASSWORD': unquote(parts.password or ''),
        'HOST': host,
        'PORT': str(port) if port else '',
    }

    if query.get('sslmode'):
        database['OPTIONS'] = {'sslmode': query['sslmode'][0]}

    if query.get('conn_max_age'):
        try:
            conn_max_age = int(query['conn_max_age'][0])
        except ValueError:
            raise ImproperlyConfigured(
                'DATABASE_URL: conn_max_age query parameter must be an '
                f'integer number of seconds (got: {query["conn_max_age"][0]!r}).'
            )
        if conn_max_age < 0:
            raise ImproperlyConfigured(
                'DATABASE_URL: conn_max_age must be >= 0 (0 = close after '
                'each request, N = keep the connection open for N seconds).'
            )
        database['CONN_MAX_AGE'] = conn_max_age

    # بررسیِ درایور در آخرین گام: خطاهایِ URL خودشان پیامِ روشن‌تر دارند؛
    # اینجا فقط مطمئن می‌شویم psycopg (نسخه‌ی ۳) واقعاً import می‌شود.
    try:
        import_module('psycopg')
    except ImportError:
        raise ImproperlyConfigured(
            'DATABASE_URL points to PostgreSQL, but the psycopg driver is '
            'not installed. Run: pip install "psycopg[binary]"  '
            '(or pip install -r requirements.txt)'
        )
    return database


DATABASES = {'default': _resolve_database()}

# هشدارِ یک‌خطی برای «Production روی SQLite»: بستنِ چشم به این حالت، یعنی
# اجرایِ نمایشیِ بدونِ کاربرِ هم‌زمان — قابل‌قبول برای دمو/دفاع، نه انتشارِ
# واقعی. فقط روی stderr نوشته می‌شود و بوت را متوقف نمی‌کند (سپرِ سختِ
# Production در بالایِ همین فایل همان‌جا که باید، ایستاده است).
if not DEBUG and DATABASES['default']['ENGINE'].endswith('sqlite3'):
    import sys as _sys
    _sys.stderr.write(
        'Warning: DJANGO_DEBUG=false is running on SQLite. This is fine for '
        'a local demo, but for real multi-user production set DATABASE_URL '
        'to a PostgreSQL server.\n'
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# این قوانین، پیش از ذخیره‌ی هر رمز عبورِ جدید بررسی می‌شوند (مثلاً نباید
# خیلی شبیهِ نامِ کاربری باشد، نباید خیلی کوتاه یا کاملاً عددی باشد و...)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# چندزبانی (از 2026-09-09): پیش‌فرضِ زبان، فارسی است. نکته‌ی طراحی: متنِ
# اصلیِ پیام‌هایِ اختصاصیِ پروژه فارسی است (نقشِ msgid در gettext)؛ برایِ
# زبانِ fa کاتالوگی در پروژه وجود ندارد، پس همان متنِ اصلی نمایش داده
# می‌شود — یعنی رفتارِ پیش‌فرض (و درخواست‌هایِ بدونِ هدرِ Accept-Language)
# دقیقاً همانِ قبل از چندزبانی‌شدن است. برایِ en، کاتالوگِ
# locale/en/LC_MESSAGES ترجمه‌ی انگلیسی را می‌دهد. پیام‌هایِ آماده‌ی خودِ
# DRF/SimpleJWT هم کاتالوگِ fa خودِ کتابخانه‌ها را می‌گیرند (قبلاً انگلیسی
# بودند؛ حالتِ fa سازگارتر با رابطِ فارسی است).
LANGUAGE_CODE = 'fa'

# زبان‌های پشتیبانی‌شده — مبنای مذاکره‌ی LocaleMiddleware رویِ Accept-Language
LANGUAGES = [
    ('fa', 'Persian'),
    ('en', 'English'),
]

# کاتالوگِ ترجمه‌ی خودِ پروژه (فعلاً فقط en؛ fa = متنِ اصلی)
LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# به جنگو می‌گوید علاوه بر فایل‌های استاتیکِ داخلِ هر اپ، پوشه‌ی static/
# پروژه (که رابط کاربریِ HTML/CSS/JS ما در آن است) را هم سرو کند. برای
# همین است که می‌شود صفحاتی مثل index.html را مستقیماً روی همین سرور
# جنگو (زیرِ آدرسِ /static/...) باز کرد.
STATICFILES_DIRS = [
    BASE_DIR.parent / 'static', 
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# اجازه می‌دهد از هر دامنه/مبدأیی (حتی وقتی فرانت‌اند روی پورتِ دیگری اجرا
# شود) به این API درخواست زده شود. مناسبِ توسعه است؛ برای انتشارِ واقعی
# باید با CORS_ALLOWED_ORIGINS به دامنه‌ی مشخصِ فرانت‌اند محدود شود.
CORS_ALLOW_ALL_ORIGINS = _env_bool('DJANGO_CORS_ALLOW_ALL', default=True)

# وقتی DJANGO_CORS_ALLOW_ALL=false است فقط این مبدأها مجازند (با کاما جدا
# کنید و scheme کامل بنویسید، مثلِ https://example.com). در حالتِ توسعه
# خالی می‌ماند چون allow-all فعال است.
CORS_ALLOWED_ORIGINS = _env_list('DJANGO_ALLOWED_ORIGINS')

# --- هدرها و تنظیماتِ امنیتیِ شرطی (از 2026-09-10) ------------------------------
# این‌ها فقط وقتی معنا دارند که سرویس واقعاً پشتِ پروکسیِ TLS (مثلِ Nginx +
# Certbot) قرار گرفته باشد — راهنمایِ گام‌به‌گام: 05_deployment.md.
# الگویِ dev-safe (نکته‌ی ۶.۱۰): همه‌ی پیش‌فرض‌ها خاموش‌اند و بدونِ ست‌کردنِ
# هیچ متغیری هیچ رفتاری عوض نمی‌شود. فعال‌کردنِ این‌ها بدونِ TLS واقعی
# یعنی قفل‌کردنِ کاربرانِ http — عمداً انتخابی است، نه اجباری.

# ریدایرکتِ http → https رویِ همه‌ی پاسخ‌ها (SecurityMiddleware)
SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', default=False)

# فلگِ Secure رویِ کوکی‌هایِ Session و CSRF — کوکیِ Secure فقط رویِ https
# فرستاده می‌شود (هر دو با یک متغیر؛ جدا‌کردنِشان فایده‌ی عملی نداشت)
SESSION_COOKIE_SECURE = _env_bool('DJANGO_COOKIES_SECURE', default=False)
CSRF_COOKIE_SECURE = _env_bool('DJANGO_COOKIES_SECURE', default=False)

# HSTS: به مرورگر اعلام می‌کند «از الان به بعد فقط https» — تا انقضایِ مدتِ
# اعلام‌شده اثرش می‌ماند و قابلِ لغوِ فوری نیست؛ فقط پشتِ TLS واقعی ست کنید
# (مقدارِ ۰ = خاموش = پیش‌فرضِ توسعه؛ یک سال = 31536000)
SECURE_HSTS_SECONDS = _env_int('DJANGO_HSTS_SECONDS', default=0)
if SECURE_HSTS_SECONDS < 0:
    raise ImproperlyConfigured(
        'DJANGO_HSTS_SECONDS must be >= 0 (0 = HSTS off; one year = 31536000). '
        'A negative duration is meaningless.'
    )

# جنگو از کدام هدرِ درخواست بفهمد که «این ترافیک https بوده» — پشتِ
# Nginx (پایان‌دهنده‌ی TLS) لازم می‌شود؛ خالی = None = رفتارِ پیش‌فرضِ
# جنگو (بدونِ پروکسی، خودِ جنگو می‌فهمد).
SECURE_PROXY_SSL_HEADER = _env_proxy_ssl_header('DJANGO_PROXY_SSL_HEADER')

# REST Framework settings
# تنظیماتِ سراسریِ DRF: همه‌ی Viewها به‌صورت پیش‌فرض این دو رفتار را دارند
# مگر این‌که در خودِ آن View چیز دیگری مشخص شده باشد.

# محدودسازیِ نرخِ درخواست (از 2026-09-10) — دفاعِ brute-force و فشارِ ناخواسته:
#  - anon: درخواست‌هایِ بی‌احرازِ هویت، به‌ازایِ هر IP (عملاً فقط مسیرهایِ
#    عمومی مثل register/login/refresh؛ بقیه قبل از throttle با 401 رد
#    می‌شوند)؛
#  - user: درخواست‌هایِ احرازِ هویت‌شده، به‌ازایِ هر کاربر؛
#  - auth: scopeِ ویژه‌ی register/login (planner/throttles.py) — پیشنهادِ
#    Production سخت‌گیرانه‌ترین مقدار باشد (حدسِ رمزِ عبور اینجاست).
# الگویِ dev-safe (نکته‌ی ۶.۱۰): بدونِ هیچ متغیری نرخ‌ها 10000/min =
# مؤثراً نامحدودند و هیچِ رفتارِ محلی عوض نمی‌شود؛ در Production با
# متغیرها فعال کنید (پیشنهاد: anon=120/min، user=600/min، auth=20/min).
# شمارنده‌ها در cacheِ پیش‌فرضِ جنگو (LocMemCache، هر فرایند جدا) نگه داشته
# می‌شوند — پشتِ چند worker گنیکورن یعنی «سقفِ هر worker»؛ جزئیاتِ صادقانه
# در 05_deployment.md.
_DEV_THROTTLE_RATE = '10000/min'
_ANON_THROTTLE_RATE = _env_throttle_rate('DJANGO_ANON_THROTTLE_RATE', _DEV_THROTTLE_RATE)
_USER_THROTTLE_RATE = _env_throttle_rate('DJANGO_USER_THROTTLE_RATE', _DEV_THROTTLE_RATE)
_AUTH_THROTTLE_RATE = _env_throttle_rate('DJANGO_AUTH_THROTTLE_RATE', _DEV_THROTTLE_RATE)

REST_FRAMEWORK = {
    # روش شناساییِ کاربر از روی هر درخواست: خواندنِ توکن JWT از هدر Authorization
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # پیش‌فرض: هیچ درخواستی بدونِ احراز هویت پذیرفته نمی‌شود (مگر با
    # @permission_classes([AllowAny]) صراحتاً اجازه داده شود، مثل register/login)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # محدودسازیِ نرخِ سراسری (از 2026-09-10) — به‌ازایِ IP برایِ بی‌احرازها
    # و به‌ازایِ کاربر برایِ احرازها؛ register/login در عوض AuthBurstThrottle
    # (scopeِ 'auth') را دارند و /api/health/ کاملاً معاف است (throttle_classes=[]).
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': _ANON_THROTTLE_RATE,
        'user': _USER_THROTTLE_RATE,
        'auth': _AUTH_THROTTLE_RATE,
    },
}

# هشدارِ یک‌خطی برایِ «Production با نرخ‌هایِ پیش‌فرضِ توسعه»: بدونِ این
# متغیرها محدودسازیِ نرخ عملاً خاموش است (10000/min) — برایِ دمو/دفاع
# قابل‌قبول، برایِ انتشارِ واقعی نه. مثلِ هشدارِ SQLite فقط رویِ stderr
# می‌نویسد و بوت را متوقف نمی‌کند (سپرِ سختِ Production بالایِ همین فایل
# سرِ جایش ایستاده است).
if not DEBUG and (
    _ANON_THROTTLE_RATE == _DEV_THROTTLE_RATE
    and _USER_THROTTLE_RATE == _DEV_THROTTLE_RATE
    and _AUTH_THROTTLE_RATE == _DEV_THROTTLE_RATE
):
    import sys as _sys
    _sys.stderr.write(
        'Warning: DJANGO_DEBUG=false is running with development-default '
        'throttle rates (10000/min = effectively unlimited). For real '
        'deployment set DJANGO_ANON_THROTTLE_RATE, DJANGO_USER_THROTTLE_RATE '
        'and DJANGO_AUTH_THROTTLE_RATE (e.g. 120/min, 600/min, 20/min).\n'
    )

# JWT settings
from datetime import timedelta

# تنظیماتِ کتابخانه‌ی djangorestframework-simplejwt
SIMPLE_JWT = {
    # توکنِ «دسترسی» که در هر درخواست فرستاده می‌شود، ۱ روز اعتبار دارد
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    # توکنِ «تمدید» که برای گرفتنِ توکنِ دسترسیِ تازه استفاده می‌شود، ۷ روز اعتبار دارد
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # چرخشِ توکنِ Refresh (از 2026-09-08): هر تمدید، علاوه بر توکنِ دسترسیِ
    # تازه، یک توکنِ Refreshِ تازه هم صادر می‌کند؛ فرانت‌اند آن را ذخیره
    # می‌کند (تابعِ refreshAccessToken در app.js از قبل آماده بود).
    'ROTATE_REFRESH_TOKENS': True,
    # توکنِ Refreshِ «قبلی» بلافاصله بعد از چرخش باطل می‌شود (لیستِ سیاه)؛
    # یعنی هر توکنِ تمدید فقط یک‌بار قابلِ استفاده است — توکنِ دزدیده‌شده
    # با اولین تمدیدِ مالکِ واقعی، بی‌اعتبار می‌شود. خروجِ سرور-محور هم
    # (POST /api/auth/logout/) با همین سازوکار توکن را باطل می‌کند.
    'BLACKLIST_AFTER_ROTATION': True,
    # یعنی هدر باید به‌شکلِ Authorization: Bearer <token> فرستاده شود
    'AUTH_HEADER_TYPES': ('Bearer',),
}
